import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex gap-2 justify-center bg-black text-white">
            <li className="hover:bg-slate-500 rounded-md">
              <a href="/">Home</a>
            </li>
            <li className="hover:bg-slate-500 rounded-md">
              <a href="/ingresar">Ingresar</a>
            </li>
            <li className="hover:bg-slate-500 rounded-md">
              <a href="/articulos">Articulos</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
